version: '3.8'
volumes:
  db-store:
    driver: local
services:
  db:
    image: postgres:15.2
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${POSTGRES_TZ}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
